### ISSUE TITLE
Promotion dialog component?

### ISSUE THREAD

**Issue by buhodev** [gtim/svelte-chessground#3]
Hey, thank you very much for this library! I am using it to build a simple online chess game. I managed to hack one of the examples to automatically promote pawns into queens, but it would be nice to have a PromotionDialog component or an example on how to implement it :)

**Comment by gtim** [comment]
Hi @buhodev and thank you! Promotion dialog is a great suggestion. I want to keep this library a thin wrapper for the original Lichess chessground, but I'm writing a more "game-ready" component over at [gtim/svelte-chess](https://github.com/gtim/svelte-chess) that will include promotion dialog, allowing only legal moves, mate/draw events, check-square color etc by default. I hope you'll find that one useful, I'll give you a ping when I get to the promotion dialog part.

Cheers
